### ISSUE TITLE
 How do I change the language of Showing X to X of X Entries

### ISSUE THREAD

**Issue by edwingromero** [jamesdordoy/laravel-vue-datatable#107]
I want to change the language of the information pagination

![image](https://user-images.githubusercontent.com/4934593/99491448-c468a880-2939-11eb-88ac-46c3a7829d55.png)

**Comment by roenfeldt** [comment]
I subscribe. The documentation is poorly written, as in, lacking important information.

**Comment by jamesdordoy** [comment]
Hi @edwingromero,

This isn't currently possible but ill look to add the functionality to do this in the next set of releases.

Thanks

**Comment by IsidroMar95** [comment]
hey @jamesdordoy whats up bro? shall we continue with the project? ✌🏾

**Comment by jamesdordoy** [comment]
@IsidroMar95 Hey mate,

Ill email you shortly.

**Comment by roenfeldt** [comment]
@edwingromero ,

Unless your app is multilingual, you could get around this issue by simply modifying the appropriate strings directly in the source, that is, `node_modules/laravel-vue-datatable/dist/laravel-vue-datatable.common.js` on line 12148 (or just search for the `Showing` string within that particular file and replacing each static instance of the phrase accordingly). Similarly to what I did (but pay attention to any existing space chars, so that you don't end up deleting them):
<img width="1169" alt="Screen Shot 2020-11-23 at 10 26 49" src="https://user-images.githubusercontent.com/60813178/99946720-83302880-2d7f-11eb-89ec-dfdf2fda87f6.png">

I know it's a quick-n-dirty hack, but it's good enough for me at this point, or at least until @jamesdordoy adds these to the translatable strings list. Hope this helps :)

**Comment by hayat97** [comment]
the other way to do it is by specify the pagination slot on your own. I think it is the cleaner way to do now.

```
<div slot="pagination" slot-scope="{ meta = {} }">
                <nav class="row">
                    <div class="col-md-4 text-left">
                        <span>
                            Memaparkan {{ meta.from }} ke {{ meta.to }} dari {{ meta.total }} rekod
                        </span>
                    </div>
                    <div class="col-md-8 text-right">
                        <pagination :links="meta.links"  />  
                    </div>
                </nav>
            </div>
```

**Comment by jamesdordoy** [comment]
Going to include translations in the next release. Dont know how so open to ideas of how to best do it
