### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'draw' of undefined

### ISSUE THREAD

**Issue by hitesh1696** [jamesdordoy/laravel-vue-datatable#115]
i'm getting this error

**Comment by jamesdordoy** [comment]
This looks like you have omitted the API resource or do not have the backend route set up correctly.

**Comment by FlavioSB** [comment]
I'm getting the same error. Imported it like this:
```
import DataTable from 'laravel-vue-datatable';
Vue.use(DataTable);
```
And used it like this:
```
<data-table
    :columns="columns"
    url="/api/user">
</data-table>
```
The "columns" object is defined and the API endpoint "/api/user" works. I tried with other APIs, same error.
Could it be that this package is outdated / not working properly anymore? 
Because I used the package in the simplest way possible (as seen above). Probably some conflict with other packages or something like that.
