### ISSUE TITLE
...has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by IsidroMar95** [jamesdordoy/laravel-vue-datatable#55]
I'm using BrowserSync to test my app on different devices, so it generates a different ip to my domain, e.g: 
`http://192.168.100.14:3000`

When loading the data does not send CORS error, but when I make use of pagination, filters and search i see that there is CORS problem
![image](https://user-images.githubusercontent.com/23019968/74180732-a2e9cc00-4c05-11ea-9bf0-5b018896d954.png)

i tried to use a [package ](https://github.com/spatie/laravel-cors) to handle the CORS and I allow the requests from any origin

```php
   'allow_origins' => [
        '*',
   ],
```
seems to work, but then it sends authorization error (401)
![image](https://user-images.githubusercontent.com/23019968/74181403-e1cc5180-4c06-11ea-8a6a-9f84cbbc8832.png)
![image](https://user-images.githubusercontent.com/23019968/74181470-fc9ec600-4c06-11ea-9562-5e72a883d1dd.png)

it's important to clarify that this doesn't happen when I'm using the app from normal domain e.g:
`https://kbis.test/`

**Comment by jamesdordoy** [comment]
Ahh thanks for the screenshots.

You have a CORS error on the Laravel backend of your app.

Have a look at this to fix the issue: https://github.com/spatie/laravel-cors
.

The issue is due to your apps not being on the same localhost server.

If your using Passport then you need to move the route out of your auth if
it should be publicly available.

**Comment by jamesdordoy** [comment]
I couldn't replicate your issue before hand.

**Comment by jamesdordoy** [comment]
Hey @IsidroMar95,

Apologies for the incorrect comments. The issue popped up as an email and i thought you had emailed me.

I can't class this as an issue with the package as this is a CORS error. The issue is that you are requesting data from a different server as you may know but this isn't related to the implementation of the package.

You can use your own requests as shown with this example if you need to pass your own headers in your request [https://jamesdordoy.github.io/laravel-vue-datatable/examples/own-data](https://jamesdordoy.github.io/laravel-vue-datatable/examples/own-data). If your using JWT tokens etc.

Feel free to email me if you need any other advise.
